/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.sort;


import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import ru.otus.ChessPlayer;

import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertTrue;


public class SortTest {
    private static final String STANDARD_RATING = "standard_rating_list.txt";

    @ParameterizedTest
    @MethodSource("chessPlayerProvider")
    public void invertionSort(List<ChessPlayer> list) {

        Comparator<ChessPlayer> comparator = ChessPlayer.RATING_DESC;
        Sort.inversion(list, comparator);
        assertTrue(Sort.isSorted(list, comparator));
    }

    private static Stream<List<ChessPlayer>> chessPlayerProvider() {
        return Stream.of(ChessPlayer.load(STANDARD_RATING, 1000));
    }
}